# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    app_bundle.listener.removed_file_listener:
        class: AppBundle\EventListener\RemovedFileListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: vich_uploader.post_remove, method: onPostRemove }

    unseen_count:
        class: AppBundle\Utils\HistoryUnseenCount
        arguments: ["@doctrine.orm.entity_manager"]
