# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    app_bundle.listener.softdelete_listener:
        class: AppBundle\EventListener\SoftDeleteListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    unseen_count:
        class: AppBundle\Utils\HistoryUnseenCount
        arguments: ["@doctrine.orm.entity_manager"]

    my_user_provider:
        class: "%my_user_provider.class%"
        arguments:
            - '@fos_user.user_manager'
            - {facebook: facebook_id}

    data_fixtures.provider.item:
            class: AppBundle\DataFixtures\ItemProvider
            tags: [ { name: nelmio_alice.faker.provider } ]
